// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

contract AAVE {

  constructor() {}

  // @notice Extracts the profit for the caller.
  // @dev Withdraw the profit made by the caller from investments or other earnings.
  // This function allows users to withdraw their profit from the contract.
  function claim() public { }

  // @notice Withdraws the principal amount.
  // @dev Allows the user to withdraw their original investment.
  // This function enables users to retrieve their initial capital invested into the contract.
  function claimBase() public { }

  // @notice Retrieves the static income.
  // @dev Returns the static income generated by the contract for the caller.
  // This function calculates and returns the fixed/static income that has been accumulated for the caller.
  // @return uint256 The amount of static income earned by the caller.
  function getIncome() public view returns(uint256) { }

}
